# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_look', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stats',
            field=models.BooleanField(default=True),
        ),
    ]
